DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    release_year      INT NOT NULL,
    rated     VARCHAR(50),
    released  VARCHAR(50),
    runtime   VARCHAR(50),
    genre     VARCHAR(255),
    director  VARCHAR(255) NOT NULL,
    writer    VARCHAR(255),
    actors    VARCHAR(255)
);

CREATE INDEX idx_movies_director ON movies(director);
